bug fix

diff --git a/.github/actions/build/action.yml b/.github/actions/build/action.yml
--- a/.github/actions/build/action.yml
+++ b/.github/actions/build/action.yml
@@ -1,207 +1,218 @@
 
-name: Build Boot Image with FastRPC Modules
+name: build
+description: Build Boot Image with FastRPC Modules
 
-on:
-  push:
-    branches:
-      - 'main'
-      - 'development'
-  pull_request:
-    branches:
-      - 'main'
-      - 'development'
-  workflow_call:
-    inputs:
-      DEVICE_TYPE:
-        required: true
-        type: string
+inputs:
+  DEVICE_TYPE:
+    description: Target device type
+    required: true
+  adsp_path:
+    description: ADSP path
+    required: true
+  cdsp_path:
+    description: CDSP path
+    required: true
+  firmware_path:
+    description: Firmware path
+    required: true
 
-jobs:
-  build:
-    runs-on: ubuntu-22.04
-    container:
-      image: lineageos4microg/docker-lineage-cicd:latest
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+runs:
+  using: "composite"
+  steps:
+  - name: Checkout repository
+    uses: actions/checkout@v2
 
-    - name:  Build Boot Image with FastRPC Modules for ${{ inputs.DEVICE_TYPE }}
-      run: |
-        echo "Build Boot Image with FastRPC Modules for ${{ inputs.DEVICE_TYPE }}"
+  - name:  Build Boot Image with FastRPC Modules 
+    shell: bash
+    run: |
+      CLEAN_DEVICE_TYPE=$(echo "${{ inputs.DEVICE_TYPE }}" | tr -d '\r')
+      CLEAN_ADSP_PATH=$(echo "${{ inputs.adsp_path }}" | tr -d '\r')
+      CLEAN_CDSP_PATH=$(echo "${{ inputs.cdsp_path }}" | tr -d '\r')
+      CLEAN_FIRMWARE_PATH=$(echo "${{ inputs.firmware_path }}" | tr -d '\r')
+      echo "Build Boot Image with FastRPC Modules for $CLEAN_DEVICE_TYPE $CLEAN_ADSP_PATH $CLEAN_CDSP_PATH $CLEAN_FIRMWARE_PATH ${{ inputs.adsp_path }}"
 
-    - name: 1. Install yq and Python tools (without sudo)
-      run: |
-        wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O yq
-        chmod +x yq
-        mv yq /usr/local/bin/yq || mv yq ./yq  # fallback if /usr/local/bin is not writable
-        apt-get update && apt-get install -y python3 python3-pip
-        python3 --version
-        pip3 --version
-        # pip3 install intelhex gki
+  - name: 1. Install yq and Python tools (without sudo)
+    shell: bash
+    run: |
+      wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O yq
+      chmod +x yq
+      mv yq /usr/local/bin/yq || mv yq ./yq  # fallback if /usr/local/bin is not writable
+      apt-get update && apt-get install -y python3 python3-pip
+      python3 --version
+      pip3 --version
+      # pip3 install intelhex gki
 
-    - name: 2. Install mkbootimg from AOSP (manual setup)
-      run: |
-        apt-get update && apt-get install -y python3-pip git
-        pip install intelhex
-        git clone https://android.googlesource.com/platform/system/tools/mkbootimg
-        export PYTHONPATH=$PWD/mkbootimg:$PYTHONPATH
-        cp mkbootimg/mkbootimg.py /usr/local/bin/mkbootimg || cp mkbootimg/mkbootimg.py ./mkbootimg
-        chmod +x /usr/local/bin/mkbootimg || chmod +x ./mkbootimg
+  - name: 2. Install mkbootimg from AOSP (manual setup)
+    shell: bash
+    run: |
+      apt-get update && apt-get install -y python3-pip git
+      pip install intelhex
+      git clone https://android.googlesource.com/platform/system/tools/mkbootimg
+      export PYTHONPATH=$PWD/mkbootimg:$PYTHONPATH
+      cp mkbootimg/mkbootimg.py /usr/local/bin/mkbootimg || cp mkbootimg/mkbootimg.py ./mkbootimg
+      chmod +x /usr/local/bin/mkbootimg || chmod +x ./mkbootimg
 
-    - name: 3. Install build dependencies (without sudo)
-      run: |
-        apt-get update && apt-get install -y gh \
-        build-essential gcc g++ make autoconf automake libtool \
-        libelf-dev flex bison tar xz-utils llvm clang lld llvm-dev \
-        util-linux initramfs-tools
+  - name: 3. Install build dependencies (without sudo)
+    shell: bash
+    run: |
+      apt-get update && apt-get install -y gh \
+      build-essential gcc g++ make autoconf automake libtool \
+      libelf-dev flex bison tar xz-utils llvm clang lld llvm-dev \
+      util-linux initramfs-tools
 
-    - name: 4. Use DSP paths if available
-      id: config
-      run: |
-        [[ -n "${{ needs.loading.outputs.adsp_path }}" ]] && echo "adsp=${{ needs.loading.outputs.adsp_path }}" >> $GITHUB_OUTPUT
-        [[ -n "${{ needs.loading.outputs.cdsp_path }}" ]] && echo "cdsp=${{ needs.loading.outputs.cdsp_path }}" >> $GITHUB_OUTPUT
-        [[ -n "${{ needs.loading.outputs.gdsp_path }}" ]] && echo "GDSP=${{ needs.loading.outputs.gdsp_path }}" >> $GITHUB_OUTPUT
-        [[ -n "${{ needs.loading.outputs.pdsp_path }}" ]] && echo "PDSP=${{ needs.loading.outputs.pdsp_path }}" >> $GITHUB_OUTPUT
-        [[ -n "${{ needs.loading.outputs.firmware_path }}" ]] && echo "firmware=${{ needs.loading.outputs.firmware_path }}" >> $GITHUB_OUTPUT
+  - name: 5. Download Linaro tools and untar
+    shell: bash
+    run: |
+      wget -c https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu.tar.xz
+      tar xf gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu.tar.xz
 
-    - name: 5. Download Linaro tools and untar
-      run: |
-        wget -c https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu.tar.xz
-        tar xf gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu.tar.xz
+  - name: 6. Set Up Build Environment and compile code for LE platform
+    shell: bash
+    run: |
+      # Set Up Build Environment
+      export PATH="$PWD/gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu/bin/:$PATH"
+      export CC=aarch64-linux-gnu-gcc
+      export CXX=aarch64-linux-gnu-g++
+      export AS=aarch64-linux-gnu-as
+      export LD=aarch64-linux-gnu-ld
+      export RANLIB=aarch64-linux-gnu-ranlib
+      export STRIP=aarch64-linux-gnu-strip
+      
+      # Compile the source code
+      chmod 777 gitcompile
+      ./gitcompile --host=aarch64-linux-gnu
 
-    - name: 6. Set Up Build Environment and compile code for LE platform
-      run: |
-        # Set Up Build Environment
-        export PATH="$PWD/gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu/bin/:$PATH"
-        export CC=aarch64-linux-gnu-gcc
-        export CXX=aarch64-linux-gnu-g++
-        export AS=aarch64-linux-gnu-as
-        export LD=aarch64-linux-gnu-ld
-        export RANLIB=aarch64-linux-gnu-ranlib
-        export STRIP=aarch64-linux-gnu-strip
-        
-        # Compile the source code
-        chmod 777 gitcompile
-        ./gitcompile --host=aarch64-linux-gnu
+  - name: 7. Verify fastrpc compiled binaries
+    shell: sh
+    run: |
+      echo "Verify the compiled binaries"
+      Files="src/.libs/libadsp_default_listener.so
+      src/.libs/libadsprpc.so
+      src/.libs/libcdsp_default_listener.so
+      src/.libs/libcdsprpc.so
+      src/.libs/libsdsp_default_listener.so
+      src/.libs/libsdsprpc.so
+      src/adsprpcd
+      src/cdsprpcd
+      src/sdsprpcd"
+  
+      for File in $Files
+      do 
+        if [ -f "$File" ]; then
+          echo "$File - Exists"
+        else
+          echo "$File - Not Exists"
+          exit 1
+        fi
+      done
 
-    - name: 7. Verify fastrpc compiled binaries
-      shell: sh
-      run: |
-        echo "Verify the compiled binaries"
-        Files="src/.libs/libadsp_default_listener.so
-        src/.libs/libadsprpc.so
-        src/.libs/libcdsp_default_listener.so
-        src/.libs/libcdsprpc.so
-        src/.libs/libsdsp_default_listener.so
-        src/.libs/libsdsprpc.so
-        src/adsprpcd
-        src/cdsprpcd
-        src/sdsprpcd"
+  - name: 8. Create directories and verify required directories
+    shell: bash
+    run: |
+      # Create directories
+      mkdir -p firmware_dir/usr/lib/dsp/adsp
+      mkdir -p firmware_dir/usr/lib/dsp/cdsp
+      mkdir -p firmware_dir/lib/firmware/qcom/$CLEAN_DEVICE_TYPE
+      mkdir -p fastrpc_dir/usr/lib
+      mkdir -p fastrpc_dir/usr/bin
+
+      # Verify directory structure
+      echo "Verifying created directories:"
+      for dir in \
+        firmware_dir/usr/lib/dsp/adsp \
+        firmware_dir/usr/lib/dsp/cdsp \
+        firmware_dir/lib/firmware/qcom/$CLEAN_DEVICE_TYPE \
+        fastrpc_dir/usr/lib \
+        fastrpc_dir/usr/bin
+      do
+        if [ -d "$dir" ]; then
+          echo "[OK] $dir exists"
+        else
+          echo "[ERROR] $dir is missing"
+          exit 1
+        fi
+      done
+
+  - name: 9. Copy fastrpc binary and fastrpc test binary
+    shell: bash
+    run: |
+      # Copy fastrpc binary
+      cp -rf src/.libs/libadsp_default_listener.so* fastrpc_dir/usr/lib/
+      cp -rf src/.libs/libadsprpc.so* fastrpc_dir/usr/lib/
+      cp -rf src/.libs/libcdsp_default_listener.so* fastrpc_dir/usr/lib/
+      cp -rf src/.libs/libcdsprpc.so* fastrpc_dir/usr/lib/
+      cp -rf src/.libs/libsdsp_default_listener.so* fastrpc_dir/usr/lib/
+      cp -rf src/.libs/libsdsprpc.so* fastrpc_dir/usr/lib/
     
-        for File in $Files
-        do 
-          if [ -f "$File" ]; then
-            echo "$File - Exists"
-          else
-            echo "$File - Not Exists"
-            exit 1
-          fi
-        done
+      cp -rf src/adsprpcd src/cdsprpcd src/sdsprpcd fastrpc_dir/usr/bin/
 
-    - name: 8. Create directories and verify required directories
-      run: |
-        # Create directories
-        mkdir -p firmware_dir/usr/lib/dsp/adsp
-        mkdir -p firmware_dir/usr/lib/dsp/cdsp
-        mkdir -p firmware_dir/lib/firmware/qcom/${{ inputs.DEVICE_TYPE }}
-        mkdir -p fastrpc_dir/usr/lib
-        mkdir -p fastrpc_dir/usr/bin
+      # Copy fastrpc test binary
+      cp -rf test/fastrpc_test fastrpc_dir/usr/bin
+      cp -rf test/linux/* fastrpc_dir/usr/bin
+      cp -rf test/v75/* fastrpc_dir/usr/bin
 
-        # Verify directory structure
-        echo "Verifying created directories:"
-        for dir in \
-          firmware_dir/usr/lib/dsp/adsp \
-          firmware_dir/usr/lib/dsp/cdsp \
-          firmware_dir/lib/firmware/qcom/${{ inputs.DEVICE_TYPE }} \
-          fastrpc_dir/usr/lib \
-          fastrpc_dir/usr/bin
-        do
-          if [ -d "$dir" ]; then
-            echo "[OK] $dir exists"
-          else
-            echo "[ERROR] $dir is missing"
-            exit 1
-          fi
-        done
+      echo "Listing contents of ./fastrpc_dir"
+      find ./fastrpc_dir
+      cd fastrpc_dir 
+      find . | cpio -o -H newc | gzip -9 > ../fastrpc.cpio.gz
+      cd ..
 
-    - name: 9. Copy fastrpc binary and fastrpc test binary
-      run: |
-        # Copy fastrpc binary
-        cp -rf src/.libs/libadsp_default_listener.so fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libadsprpc.so fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libcdsp_default_listener.so fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libcdsprpc.so fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libsdsp_default_listener.so fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libsdsprpc.so fastrpc_dir/usr/lib/
+  - name: 10. Download hexagon-dsp-binaries
+    shell: bash
+    run: |
+      git clone https://github.com/linux-msm/hexagon-dsp-binaries.git
+      ls -la hexagon-dsp-binaries
 
-        cp -rf src/.libs/libadsp_default_listener.so.1 fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libadsprpc.so.1 fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libcdsp_default_listener.so.1 fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libcdsprpc.so.1 fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libsdsp_default_listener.so.1 fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libsdsprpc.so.1 fastrpc_dir/usr/lib/
-        
-        cp -rf src/.libs/libadsp_default_listener.so.1.0.0 fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libadsprpc.so.1.0.0 fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libcdsp_default_listener.so.1.0.0 fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libcdsprpc.so.1.0.0 fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libsdsp_default_listener.so.1.0.0 fastrpc_dir/usr/lib/
-        cp -rf src/.libs/libsdsprpc.so.1.0.0 fastrpc_dir/usr/lib/
-        
-        cp -rf src/adsprpcd fastrpc_dir/usr/bin/
-        cp -rf src/cdsprpcd fastrpc_dir/usr/bin/
-        cp -rf src/sdsprpcd fastrpc_dir/usr/bin/
+      CLEAN_DEVICE_TYPE=$(echo "${{ inputs.DEVICE_TYPE }}" | tr -d '\r')
+      CLEAN_ADSP_PATH=$(echo "${{ inputs.adsp_path }}" | tr -d '\r\n')
+      CLEAN_CDSP_PATH=$(echo "${{ inputs.cdsp_path }}" | tr -d '\r')
+      CLEAN_FIRMWARE_PATH=$(echo "${{ inputs.firmware_path }}" | tr -d '\r')
+      echo "Build Boot Image with FastRPC Modules for $CLEAN_DEVICE_TYPE $CLEAN_ADSP_PATH $CLEAN_CDSP_PATH $CLEAN_FIRMWARE_PATH ${{ inputs.adsp_path }}"
 
-         # Copy fastrpc test binary
-        cp -rf test/fastrpc_test fastrpc_dir/usr/bin
-        cp -rf test/linux/* fastrpc_dir/usr/bin
-        cp -rf test/v75/* fastrpc_dir/usr/bin
+      cp -rf ${{ inputs.adsp_path }}/* firmware_dir/usr/lib/dsp/adsp
+      ls -la firmware_dir/usr/lib/dsp/adsp
 
-        echo "Listing contents of ./fastrpc_dir"
-        find ./fastrpc_dir
-        cd fastrpc_dir 
-        find . | cpio -o -H newc | gzip -9 > ../fastrpc.cpio.gz
-        cd ..
+      cp -rf ${{ inputs.cdsp_path }}/* firmware_dir/usr/lib/dsp/cdsp
+      ls -la firmware_dir/usr/lib/dsp/cdsp
 
-    - name: 10. Download hexagon-dsp-binaries
-      run: |
-        git clone https://github.com/linux-msm/hexagon-dsp-binaries.git
-        ls -la hexagon-dsp-binaries
-        cp ${{ steps.config.outputs.adsp }}/* firmware_dir/usr/lib/dsp/adsp
-        cp ${{ steps.config.outputs.cdsp }}/* firmware_dir/usr/lib/dsp/cdsp
 
-    - name: 11. Download dsp-linux-firmware
-      run: |
-        git clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
-        ls -la linux-firmware
-        cp -rf ${{ steps.config.outputs.firmware }}/* firmware_dir/lib/firmware/qcom/${{ inputs.DEVICE_TYPE }}/
-        mv firmware_dir/lib/firmware/qcom/${{ inputs.DEVICE_TYPE }}/Thundercomm/RB5/* firmware_dir/lib/firmware/qcom/${{ inputs.DEVICE_TYPE }}/
+  - name: 11. Download dsp-linux-firmware
+    shell: bash
+    run: |
+      git clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
+      ls -la linux-firmware
+      CLEAN_FIRMWARE_PATH=$(echo "${{ inputs.firmware_path }}" | tr -d '\r')
 
-    - name: 12. list and create a zip file of dsp-firware
-      run: |
-        echo "Listing contents of ./firmware_dir"
-        find ./firmware_dir
-        cd firmware_dir
-        find . | cpio -o -H newc | gzip -9 > ../dsp-firmware.cpio.gz
-        cd ..
+      cp -rf ${{ inputs.firmware_path }}/* firmware_dir/lib/firmware/qcom/$CLEAN_DEVICE_TYPE/
+      ls -la firmware_dir/lib/firmware/qcom/$CLEAN_DEVICE_TYPE/
 
-    - name: 13. Upload Compiled fastrpc binaries
-      id: upload_boot_img
-      uses: actions/upload-artifact@v4
-      with:
-        name: fastrpc-artifacts
-        path: |
-          ${{ github.workspace }}/dsp-firmware.cpio.gz
-          ${{ github.workspace }}/fastrpc.cpio.gz
-        retention-days: 1
+      # Move Thundercomm RB5 firmware files if available
+      SOURCE_DIR="firmware_dir/lib/firmware/qcom/$CLEAN_DEVICE_TYPE/Thundercomm/RB5"
+      TARGET_DIR="firmware_dir/lib/firmware/qcom/$CLEAN_DEVICE_TYPE"
 
+      if [ -d "$SOURCE_DIR" ] && [ "$(ls -A $SOURCE_DIR)" ]; then
+        echo "Moving files from $SOURCE_DIR to $TARGET_DIR"
+        mv "$SOURCE_DIR"/* "$TARGET_DIR"/
+      else
+        echo "No files to move from $SOURCE_DIR"
+      fi
+
+
+  - name: 12. list and create a zip file of dsp-firmware
+    shell: bash
+    run: |
+      echo "Listing contents of ./firmware_dir"
+      find ./firmware_dir
+      cd firmware_dir
+      find . | cpio -o -H newc | gzip -9 > ../dsp-firmware.cpio.gz
+      cd ..
+
+  - name: Upload Compiled fastrpc binaries
+    uses: actions/upload-artifact@v4
+    with:
+      name: fastrpc-artifacts
+      path: |
+        ${{ github.workspace }}/dsp-firmware.cpio.gz
+        ${{ github.workspace }}/fastrpc.cpio.gz
+      retention-days: 1
+      overwrite: true
