Validate kernel and dtb paths

diff --git a/.github/workflows/sa8775p-fastrpc-bootimg-builder.yml b/.github/workflows/sa8775p-fastrpc-bootimg-builder.yml
--- a/.github/workflows/sa8775p-fastrpc-bootimg-builder.yml
+++ b/.github/workflows/sa8775p-fastrpc-bootimg-builder.yml
@@ -159,10 +159,14 @@ jobs:
           gh run download 15867457800 --repo quic/fastrpc --name linux-kernel-artifacts --dir ./linux-kernel-artifacts
 
       # Step 13.1: Validate kernel and dtb paths
-      - name: 13.1. Validate kernel and dtb paths
+      - name: Validate artifact download
         run: |
-          test -f linux-kernel-artifacts/tar-install/arch/arm64/boot/Image
-          test -f linux-kernel-artifacts/arch/arm64/boot/dts/qcom/sa8775p-ride.dtb
+          if [ -f ./linux-kernel-artifacts/arch/arm64/boot/Image ]; then
+            echo "✅ Artifact downloaded successfully and Image file exists."
+          else
+            echo "❌ Artifact download failed or expected file not found."
+            exit 1
+          fi
 
       # Step 14: Create ramdisk file including fastrpc binaries
       - name: 14. Create ramdisk file including fastrpc binaries
diff --git a/.github/workflows/sm8250-fastrpc-bootimg-builder.yml b/.github/workflows/sm8250-fastrpc-bootimg-builder.yml
--- a/.github/workflows/sm8250-fastrpc-bootimg-builder.yml
+++ b/.github/workflows/sm8250-fastrpc-bootimg-builder.yml
@@ -41,7 +41,7 @@ jobs:
 
     - name: 3. Install build dependencies (without sudo)
       run: |
-        apt-get update && apt-get install -y \
+        apt-get update && apt-get install -y gh \
         build-essential gcc g++ make autoconf automake libtool \
         libelf-dev flex bison tar xz-utils llvm clang lld llvm-dev \
         util-linux initramfs-tools
@@ -191,12 +191,14 @@ jobs:
 
 
     # Step 13.1: Validate kernel and dtb paths
-    - name: 13.1. Validate kernel and dtb paths
+    - name: Validate artifact download
       run: |
-        cd linux-kernel-artifacts
-        test -f tar-install/lib/modules
-        test -f arch/arm64/boot/Image
-        test -f arch/arm64/boot/dts/qcom/sm8250-mtp.dtb
+        if [ -f ./linux-kernel-artifacts/arch/arm64/boot/Image ]; then
+          echo "✅ Artifact downloaded successfully and Image file exists."
+        else
+          echo "❌ Artifact download failed or expected file not found."
+          exit 1
+        fi
 
     - name: 13. Download and create fastrpc included ramdisk file
       run: |
